### PR TITLE
initialization commit

### PR DESCRIPTION
**Pull request by cbendot**

### CODE REVIEW

**Review by celtare21 — APPROVED** [review]
Looks good too me. 11/10, would merge again!

**Comment by mortezadadgar** [comment]
This's what needed all these years MERGE!

**Comment by Panchajanya1999** [comment]
@cbendot is god !

**Comment by uditkarode** [comment]
Perfect, we need this on all the repos!

**Comment by nobodyknowsmyname** [comment]
SHUT UP LOL

**Comment by Lyceris-chan** [comment]
@renascape hello

**Comment by nobodyknowsmyname** [comment]
> @renascape hello
> 

Hlo

**Pull request closed without merging**
